/* Generated By:JavaCC: Do not edit this line. FunConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FunConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MULTIPLY = 8;
  /** RegularExpression Id. */
  int DIVIDE = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int GT = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int EQ = 13;
  /** RegularExpression Id. */
  int LE = 14;
  /** RegularExpression Id. */
  int GE = 15;
  /** RegularExpression Id. */
  int NEQ = 16;
  /** RegularExpression Id. */
  int REM = 17;
  /** RegularExpression Id. */
  int NOT = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int XOR = 21;
  /** RegularExpression Id. */
  int PWR = 22;
  /** RegularExpression Id. */
  int BREAK = 23;
  /** RegularExpression Id. */
  int CLASS = 24;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int EXTENDS = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int INT = 31;
  /** RegularExpression Id. */
  int NEW = 32;
  /** RegularExpression Id. */
  int PRINT = 33;
  /** RegularExpression Id. */
  int READ = 34;
  /** RegularExpression Id. */
  int RETURN = 35;
  /** RegularExpression Id. */
  int STRING = 36;
  /** RegularExpression Id. */
  int SUPER = 37;
  /** RegularExpression Id. */
  int FLOAT = 38;
  /** RegularExpression Id. */
  int BOOLEAN = 39;
  /** RegularExpression Id. */
  int CHAR = 40;
  /** RegularExpression Id. */
  int LPAREN = 41;
  /** RegularExpression Id. */
  int RPAREN = 42;
  /** RegularExpression Id. */
  int LBRACE = 43;
  /** RegularExpression Id. */
  int RBRACE = 44;
  /** RegularExpression Id. */
  int LBRACKET = 45;
  /** RegularExpression Id. */
  int RBRACKET = 46;
  /** RegularExpression Id. */
  int SEMICOLON = 47;
  /** RegularExpression Id. */
  int COMMA = 48;
  /** RegularExpression Id. */
  int DOT = 49;
  /** RegularExpression Id. */
  int tipo_INT = 50;
  /** RegularExpression Id. */
  int tipo_FLOAT = 51;
  /** RegularExpression Id. */
  int tipo_STRING = 52;
  /** RegularExpression Id. */
  int tipo_NULL = 53;
  /** RegularExpression Id. */
  int tipo_CHAR = 54;
  /** RegularExpression Id. */
  int tipo_BOOLEAN = 55;
  /** RegularExpression Id. */
  int tipo_Identificador = 56;
  /** RegularExpression Id. */
  int LETTER = 57;
  /** RegularExpression Id. */
  int DIGIT = 58;
  /** RegularExpression Id. */
  int PUBLIC = 59;
  /** RegularExpression Id. */
  int PROTECTED = 60;
  /** RegularExpression Id. */
  int PRIVATE = 61;
  /** RegularExpression Id. */
  int FINAL = 62;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 69;
  /** RegularExpression Id. */
  int INVALID_CONST = 70;
  /** RegularExpression Id. */
  int INVALID_CHAR = 71;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"%\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"^\"",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"while\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"string\"",
    "\"super\"",
    "\"float\"",
    "\"boolean\"",
    "\"char\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<tipo_INT>",
    "<tipo_FLOAT>",
    "<tipo_STRING>",
    "\"null\"",
    "<tipo_CHAR>",
    "<tipo_BOOLEAN>",
    "<tipo_Identificador>",
    "<LETTER>",
    "<DIGIT>",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"final\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 65>",
    "\"//\"",
    "<token of kind 67>",
    "<token of kind 68>",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
    "<INVALID_CHAR>",
  };

}
